import esbuild from "esbuild";
import process from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const isProd = process.argv[2] === "production";

const builtInModules = [
  "fs",
  "path",
  "crypto",
  "os",
  "child_process",
  "util",
  "events",
  "stream"
];

async function run() {
  const context = await esbuild.context({
    banner: {
      js: banner,
    },
    entryPoints: ["main.ts"],
    bundle: true,
    external: [
      "obsidian",
      "electron",
      "@codemirror/state",
      "@codemirror/view",
      "@lezer/common",
      "@lezer/highlight",
      "@lezer/lr",
      ...builtInModules
    ],
    format: "cjs",
    target: "es2020",
    logLevel: "info",
    sourcemap: isProd ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
  });

  if (isProd) {
    await context.rebuild();
    process.exit(0);
  } else {
    await context.watch();
  }
}

run().catch(() => process.exit(1));
